# Generated by Django 2.1 on 2018-08-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='NumberComputer',
            field=models.IntegerField(default=1, verbose_name='Номер компьютера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='NumberRoom',
            field=models.IntegerField(default=1, verbose_name='Номер комнаты'),
            preserve_default=False,
        ),
    ]
