# Generated by Django 2.1 on 2018-08-28 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupApp', '0002_auto_20180828_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='FlagTask',
            field=models.BooleanField(default='False', verbose_name='На контроле'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskExecutor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель задачи'),
        ),
    ]
